### ISSUE TITLE
questin

### ISSUE THREAD

**Issue by ctig2015** [scfmod/FS22_TerraFarm#1]
will we be able to load soil as well or just stone for now? looking  forward to seeming more progress on this scrtp big game-changer 

regard
chris the Irish gamer

**Comment by scfmod** [comment]
That is possible to do if you have a dirt fillType registered.
When you save your game the mod will create a XML config file in"../FarmingSimulator2022/modSettings/TerraFarm/config.xml"
In that file you can find fillTypeName and change it accordingly :-)

The plan is to implement a dirt fillType, but probably won't happen until GIANTS release info/tools for their array texture setup.

**Comment by ctig2015** [comment]
ah cool no worries lad still  pretty cool thing to have in-game lol no more buying lime for me now lol 😁

**Comment by scfmod** [comment]
Dirt fillType is now in testing :-)
It will add it if it doesn't already exists (some maps already provides dirt fillType). Will also be adding a setting in the GUI to make it easy to choose.

**Comment by scfmod** [comment]
More filltype features added now for ye to play with :-)
