### ISSUE TITLE
Can only "paint" not dig

### ISSUE THREAD

**Issue by Kyussbird** [scfmod/FS22_TerraFarm#10]
Hello, awesome mod. But i cant really use it.. :( When i try to use the volvo 750 with the correct bucket, (tried many wheelloaders and excavators) it doesnt pick up any stone etc, it only paints the ground with dirt. Whats the problem? Tried all versions availble, started with admin, removed all other mods, tried different maps... Could you contact me on discord? KYUSS BIRD´#3284

**Comment by Kyussbird** [comment]
![image](https://user-images.githubusercontent.com/11639037/148116342-b1754378-4822-4164-ba80-df88c6f033ee.png)

**Comment by Dzi4d3k** [comment]
I suggest to watch:
https://www.youtube.com/watch?v=mj6pPoYRiYk

**Comment by alphaomegarandomname** [comment]
Hello. There is nothing wrong with it. This happens when you use an old version of the game. You need the latest patched release. It will only paint on the initial release which i believe is what you are using :))
