### ISSUE TITLE
Alexscom D11

### ISSUE THREAD

**Issue by tmanningyo22** [scfmod/FS22_TerraFarm#103]
Hi i am trying to add the new terrafarm to alexscom d11 mod but it does not seem to be working. do you have any sugestions?

**Comment by scfmod** [comment]
Depends on how you want to integrate it, though I think there's a configuration coming in the next [Machines addon](https://github.com/scfmod/FS22_TerraFarmMachines) update (courtesy of contributions from Fallingblood). It's a huge update with 900+ new configurations so stay tuned the next couple of days :-)

**Comment by tmanningyo22** [comment]
So do I just drop it in the machine addon?

**Comment by scfmod** [comment]
Yeah you can add your own configurations into the machine addon mod. Just create a new configuration XML inside the addon mod and add an entry in "xml/machineConfigurations.xml"

**Comment by tmanningyo22** [comment]
What are the possibilities of you making a YouTube video for the rest of us
that are not super Savy with modding?

**Comment by scfmod** [comment]
Unfortunately I don't have the spare time to do that, but I'm sure someone will create some youtube guides in time :-)
If anyone is up to the task and need some technical help/details, feel free to make a post on the [discussions page](https://github.com/scfmod/FS22_TerraFarm/discussions)
