### ISSUE TITLE
On FS22_0_TerraFarmMachines the T75 trencher wont work with your settings 

### ISSUE THREAD

**Issue by Nonnus79** [scfmod/FS22_TerraFarm#104]
On FS22_0_TerraFarmMachines the T75 trencher have a node <workArea referenceNode="0>0|4|18" this node do not exist on i3d so apears on center and  dont touch on the ground.  You need move the node to the front of the chain. 

![fsScreen_2024_09_29_13_45_59](https://github.com/user-attachments/assets/22da8395-4611-4a8e-aeb1-30de1ef1b6b8)

**Comment by scfmod** [comment]
Could probably be because I'm testing with mods dated from july, was any .i3d changed?
Anyhow, if you have any suggestion for change please [post an issue here](https://github.com/scfmod/FS22_TerraFarmMachines/issues)  instead of this repo
