### ISSUE TITLE
[L10N] Translation to ES

### ISSUE THREAD

**Issue by RoberT162v** [scfmod/FS22_TerraFarm#107]
Hi, I'm sending you the Spanish translation of the mod.
Regards and thanks for the mod!!
[l10n_es.txt](https://github.com/user-attachments/files/17342895/l10n_es.txt)

**Comment by scfmod** [comment]
Cheers, will add it to next release :-)

**Comment by scfmod** [comment]
Now available in 0.9.7.0 👍
