### ISSUE TITLE
To Much Stone Generated

### ISSUE THREAD

**Issue by DrDrulia** [scfmod/FS22_TerraFarm#11]
Hey. Want to say Thank you first. What a mod!! 
after digging a hole trying to fill it back and bit sketchy. Is there a way to reduce the amount of rock getting from leveling?

**Comment by scfmod** [comment]
You can play around with fillTypeMassRatio and volumeFillRatio in the config.xml for now :-)
I'll probably implement a global variable for it a bit later on.

**Comment by DrDrulia** [comment]
Hello there

Thank you for replay. But where I can find config xml? 

Kind Regards
Vaidas Drulia
Dr.Drulia
