### ISSUE TITLE
Lack of material when trying to fill digged hole

### ISSUE THREAD

**Issue by Dzi4d3k** [scfmod/FS22_TerraFarm#13]
Hello,

First of all thank you for great mod. There is huge exponential in it, and real brings very anticipated functionality. I was wondering why such a mod didn't come out for FS19, when Giants introduced in-game landscaping, but maybe in FS19 it was not possible to landscape outside of editor.

Now watching on The FarmSim Guy's attempts to flatten hole digged earlier I wonder, why there is less material digged then needed to fill hole
[https://youtu.be/mj6pPoYRiYk?t=394](url)
IRL it is almost always more material after digging, because it is lessen and have to be compacted to fill hole that it was digged from. Now taking into account limits of landscaping in game I thing that compacting can be omitted, but at least some balancing could be done to level that difference.

**Comment by scfmod** [comment]
The issue is due to how the volume changes are calculated by GIANTS' functions, this also has variations between maps.
Balancing it further has been on the agenda since I started the mod, but can't give specific answer to when.

**Comment by scfmod** [comment]
I'll add some ratio values to config.xml so that you can play around with it in 0.3.5.0 :-)
