### ISSUE TITLE
Buckets aren't filling

### ISSUE THREAD

**Issue by Hoggie07** [scfmod/FS22_TerraFarm#15]
When I try to use anything bucket I am able to dig but the bucket does not fill all the way, typically to 1% or 2% and I don't get anything out of it. Is there something i have to do when I install or is it something I'm using. Currently using the Liebherr with the regular bucket.
https://user-images.githubusercontent.com/97237600/148398040-bc8ad5f1-f51d-4210-8c95-b428f6529fb5.jpg

**Comment by scfmod** [comment]
Have you updated to latest version of FS22? If so which map and post a link to pastebin with log.txt

**Comment by Hoggie07** [comment]
Yes I have the most recent version of the game it doesn't work on any of the maps I play on. https://pastebin.com/G3uLVcJd

**Comment by scfmod** [comment]
There's a ton of other mods loading, try with a clean savegame with only TerraFarm mod. It's a possibility that one or more of the other mods caused the issue.

**Comment by scfmod** [comment]
Closing this issue pending feedback, if you still have problems please create a new issue and reference this one.
