### ISSUE TITLE
[MP] dedicated server bug

### ISSUE THREAD

**Issue by darkpalladin12** [scfmod/FS22_TerraFarm#16]
Good day 
First thank you for this amazing mod, its a game changer and I'm absolutely loving it.

The issues I have experienced is when its hosted on a dedicated server, I used the Volvo excavator and when trying to dig it only fills up with stone and cant change fill type material and discharge the material,  however when creating my own save on my own pc on multiplayer and not on our dedicated server, the mod is working perfectly fine , can switch back and forth from all fill types and no issues with discharge.

**Comment by scfmod** [comment]
Which map did ye use on the dedicated server?
I'll look into it this weekend

**Comment by darkpalladin12** [comment]
I used Yukon valley on the dedicated server , but also tested Yukon valley map on multiplayer hosting my own game and the mod is working fine on that map.
