### ISSUE TITLE
How can i solve this problem?

### ISSUE THREAD

**Issue by Bladi18** [scfmod/FS22_TerraFarm#17]
I have downloaded the mod correctly and when I enter the game and activate it, I want to do an excavation in my own field and I cannot get material in the bucket of the machine, please help

**Comment by scfmod** [comment]
Make sure you have updated FS to 1.2.0.2 and try with a clean savegame with only TerraFarm mod activated.

**Comment by scfmod** [comment]
Closing this issue pending feedback, if you still have problems please create a new issue and reference this one.
