### ISSUE TITLE
Unable to flatten ground on pickup in tractors

### ISSUE THREAD

**Issue by KrzCze** [scfmod/FS22_TerraFarm#18]
I tried levelling the ground in a tractor with the front loader bucket and it doesn't pick up anything. Tested with different maps and tractors. 
Flattening on pickup works with all the other machines (including front loaders) and buckets. 
I attached the front loader bucket to a telehandler using an adapter mod and it worked. 
Flattening works while emptying a bucket.

All other options for the front loader bucket work. 

No errors or warnings in the game log that I can see. 

PS. I am using the most up to date game. 
PPS. Great mod!
![terrafarm_bug_small](https://user-images.githubusercontent.com/97291424/148545090-a083fdfe-6bc0-4455-bd03-3c4b1de9056c.png)

**Comment by scfmod** [comment]
Hm I think the frontloader part of the code maybe need a small rewrite :-) I'll check it up, thanks for reporting!
