### ISSUE TITLE
Unable to toggle Terrafarm on/off after reloading the game

### ISSUE THREAD

**Issue by Eddievick** [scfmod/FS22_TerraFarm#2]
Hi, Stunning work, a truly game-changing mod, I've been playing around a bit with it today, I've noticed after quitting and reloading the game, hitting Y to enable TerraFarm won't work and remains off. I can still collect stone I've already dug up but can't dig anything new.
![Farming Simulator 22 Screenshot 2022 01 03 - 20 51 28 23](https://user-images.githubusercontent.com/94964006/147979017-7fc3a2ff-1c7c-42c5-abd7-d5b81e94713a.png)

Thanks 
FSG!

**Comment by scfmod** [comment]
Hm, that's weird. Can you check the GUI menu and see if it's disabled there?
![image](https://user-images.githubusercontent.com/45406107/147980141-f4aa2a7a-63ee-4410-b3a6-51b486a71047.png)

If it's still an issue post your log.txt on pastebin and link it here, and I'll take a look :-)

**Comment by Eddievick** [comment]
Haha that's totally it, didn't realise that was a global state! nice one man

**Comment by scfmod** [comment]
Phew, dodged a bullet there 😂 I'll make sure to update the GUI soon and make it a bit clearer :-)

**Comment by vincent-17** [comment]
bonsoir je n'arrive pas a telecharger le mod terra farm merci bien

**Comment by jeremvl53** [comment]
bonjour a tous impossible d'ouvrir le menu avec f9  n'y Y pour activer ,les mods son reconnue met impossible de faire fonctionner comment faire ? merci pour l'aide

**Comment by volviczka** [comment]
dzien dobry.mam moda w grze i gra jego widzi ale nie moge go wlaczyc zadnym przyciskiem.co mam zrobic

**Comment by volviczka** [comment]
mam moda w grze i go widzi ale nie moge go wlaczyc.jak mam to zrobic

**Comment by Haandk** [comment]
Hey,
I’m having a problem where I see it in downloaded mods but not on the mod selection page after selecting a map. And no gui in game 
Can someone help?
