### ISSUE TITLE
[MP] Not changing FillType

### ISSUE THREAD

**Issue by glebreck** [scfmod/FS22_TerraFarm#23]
Using Yukon map and only digs stone with latest version.

**Comment by scfmod** [comment]
There are some issues with fillTypes other than STONE on MP as I haven't added code that synchronizes states yet.
I am currently reworking large parts of the code to support bulldozer functionality, and will add network sync code for TerraFarm Machines.
With new code machines will have independent settings for fillType, paint layers etc. which will (hopefully) completely remove these issues.

**Comment by glebreck** [comment]
Awesome! Thank you! This is a great mod!
