### ISSUE TITLE
Bucket setting enhancement

### ISSUE THREAD

**Issue by redrummed1** [scfmod/FS22_TerraFarm#24]
More of an enhancement than an issue.  

Would be nice to see in a future update where we can see what setting we are on Flatten, raise or lower ground in the bottom right where our speedometer etc. is.

A simple symbol like the one in the help menu,  it would save having to keep drop down menu open taking up valuable screen space.

Also would like to say Genius of a mod mate, love this kinda stuff and looking forward to where it goes. Finally have a use for that 2nd joystick again since I lost interest in forestry long time ago.

**Comment by scfmod** [comment]
Aye the HUD probably need a little overhaul down the line!
Sadly it won't be prioritized, but if there's any modders who want to create a simple HUD extension addon for TerraFarm to provide that functionality let me know :-)

**Comment by scfmod** [comment]
HUD improvement is being worked on for 0.4.0.0
