### ISSUE TITLE
[Mod map] tip to ground with multi-fruit

### ISSUE THREAD

**Issue by dariusfrost** [scfmod/FS22_TerraFarm#26]
Hi, I have been using and enjoying this mod greatly but i noticed an issue with the most recent update 3.6.0 that when i mow it leaves grass on the ground but has the wheat texture on the windrow. This is occuring on a multifruit map (Wolfcreek 4x) that i am testing for Dajnet that has clover windrow added as a tip to ground causing an indexing error.

**Comment by scfmod** [comment]
If you have issues with 0.3.6.0 (which adds custom map density height for DIRT - the only thing changed in that version, which may cause conflicts), I'd recommend using previous version for now. I'll look more into it when I'm done with 0.4.0.0. Thanks for reporting! :-)

**Comment by dariusfrost** [comment]
I did got back to 3.5 which works just fine

**Comment by scfmod** [comment]
With version 0.4.0.0 the functionality for adding DIRT to maps (added in 0.3.6.0) will be removed. This feature seems to be too unstable at the moment. Looking into getting a separate mod made to add this functionality. TerraFarm will still support additional fillTypes and groundTypes.
Keeping this issue open until new release.

**Comment by TrevElvis** [comment]
I can't discharge anything even though i am on my land, is there something i should do apart from tipping bucket ?

**Comment by scfmod** [comment]
If you can't tip a fillType to the ground it's because the map does not have support for it.
Closing this issue for now.
Feel free to create a new issue and reference this one if you have same problems when 0.4.0.0 is released :-)
