### ISSUE TITLE
raising ground should only be possible with shovels contents inside

### ISSUE THREAD

**Issue by alexanderweide** [scfmod/FS22_TerraFarm#29]
Hey,

i think it should be only possible to raise ground as long as some material is inside of the shovel. currently i can raise the ground by just contact with the shovel and the ground.

**Comment by scfmod** [comment]
Should be less of a problem with 0.4.0.0. I'll close this one for now, feel free to open a new issue and reference this one if you have the problem when 0.4.0.0 is released.
