### ISSUE TITLE
Cosmetic - Unload Animation

### ISSUE THREAD

**Issue by Eddievick** [scfmod/FS22_TerraFarm#3]
I'm sure you are aware of this already, just thought I'd share

https://user-images.githubusercontent.com/94964006/147979289-2cb84f1f-6c56-4280-a3cf-30538269b064.mp4

e

**Comment by scfmod** [comment]
Yeah I haven't gotten around to fix that one yet, thanks for reporting! 👍

**Comment by scfmod** [comment]
Did some research today and it seems that the animation bug is from the vehicle mods themselves, not TerraFarm.
Currently doing some more testing on it and will try to work with the authors to fix it :-)

Marking this as closed.
