### ISSUE TITLE
Read this if you have problems getting the mod working

### ISSUE THREAD

**Issue by blainegen** [scfmod/FS22_TerraFarm#30]
i have downloaded multiple times and it will pop up in the mods  but when i start a new game it dont register

**Comment by Dzi4d3k** [comment]
1. Update game (if you don't have latest patch).
2. Use guide from:
https://www.youtube.com/watch?v=JsZWSCLuXFQ

**Comment by WesleyP1984** [comment]
I have the same issue. 
The game is up to date, the map (no mans land) is up to date, When I get to the mod loading sceen I can select it but when I'm in-game it is not. 
What can be the problem here?

**Comment by TheEntityYT** [comment]
The mod isn't showing up in the mods, only in the files. Am I looking in the wrong alphabetical section?

**Comment by KosovaliBedirhan** [comment]
Bende modun menüsüne ve kuleye girdiğimde beyaz ekran gösteriyor herhangi bişey yapamıyorum nasıl düzeltebilirim
