### ISSUE TITLE
specialization request

### ISSUE THREAD

**Issue by Brundavo** [scfmod/FS22_TerraFarm#31]
Hello . would it be possible to configure the terrafarm for specialization. leveler . thanks in advance

**Comment by scfmod** [comment]
There's nothing specific for the Leveler specialization planned for now, though with 0.4.0.0 is coming a bulldozerBlade machine type you can try out (which uses the Leveler spec) :-)

**Comment by Brundavo** [comment]
Thanks

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________
