### ISSUE TITLE
[Shortcuts] Ability to change shortcut bindings

### ISSUE THREAD

**Issue by SkiDooGuy** [scfmod/FS22_TerraFarm#32]
The ability to change bindings in-game would be beyond amazing. Currently the in-game GUI is somehow bound to the z-axis on one of my joysticks, so whenever I twist even a little bit (say while using a loader or excavator) it opens the GUI rather than curling my bucket (or whatever function is close enough that the action results in some twist). I can turn my dead zones down of course, but the ability to change the key bindings would be best.

**Comment by scfmod** [comment]
Setting custom keybinds is planned for 0.4.0.0 release :-)

**Comment by SkiDooGuy** [comment]
Awesome! Thanks!
