### ISSUE TITLE
Add "Normal" to the default digging mode types

### ISSUE THREAD

**Issue by SkiDooGuy** [scfmod/FS22_TerraFarm#33]
Much like there is to empty a bucket, I would find great benefit from a "normal" option when digging.

Case example: I have been building a road bed and am bringing in material from another area on the map. It dumps out as stone, but I want it to be added to the map itself using the "raise" function in TerraFarm. As it dumps out of the truck as stone, I have to disable TF on my loader to prevent ground changes and the deletion of the stone material, then re-enable it to dump the material in the method I desire. 

If I could just scoop the stone then have the dump behavior as raise but not have to toggle TF it would save a lot of hassle. The number of accidentally dumped stone piles in awkward spots I'm trying to fill has wasted a lot more material than I'm willing to admit.

**Comment by scfmod** [comment]
Just to add for closing issue: This feature is added to 0.4.0.0 dev version.
