### ISSUE TITLE
Add Filltype Lithiumore.

### ISSUE THREAD

**Issue by Nonnus79** [scfmod/FS22_TerraFarm#34]
Hi i´m the author of MCE map and filltypesTP for FS22.
  
  On the next version of Terrafarm can you add Lithiumore as filltype?
  
I release a MCE version for use with terrafarm, but i needed edit your mod to add lithiumore. I dont want edit your mod on every version, so if you add lithiumore as filltype i´m glad.

**Comment by scfmod** [comment]
Automatic fillTypes is already added in 0.4.0.0, slated for release in a week or 2.
https://github.com/scfmod/FS22_TerraFarm/projects/1#card-75608740
