### ISSUE TITLE
Suggestion - Add language xml to the mod

### ISSUE THREAD

**Issue by TheChoseOne900** [scfmod/FS22_TerraFarm#35]
Hi, is possible to add a xml for language for people translate the mod to there native lang? Should be nice... Think about it.. xD
Love the mod and good work mate!!!

**Comment by scfmod** [comment]
Added language support yesterday for upcoming 0.4.0.0 :-)
English and french is ready, looking to add more before release

**Comment by Dzi4d3k** [comment]
I could help with Polish, but I can't find base (en) xml for localization.

**Comment by TheChoseOne900** [comment]
> Added language support yesterday for upcoming 0.4.0.0 :-) English and french is ready, looking to add more before release

Im waiting for the release to translate to pt-pt lang! =)
