### ISSUE TITLE
Issues in larger maps

### ISSUE THREAD

**Issue by fudoido** [scfmod/FS22_TerraFarm#36]
Hello team. first of thanks for this excellent mod.
There are several reports on facebook groups about the mod creating issues with straw and crops on maps larger than base size.
I am not sure what kind of issues people is referring to, as no one has given specific details, but such reports came mostly from the facebook page of the author of wild west 16x map, and someone mentioned it happens with any map larger than base size.
I will try to find specifics and report them back here, but thought i should give a heads-up already so maybe you guys can investigate.
They also mention it happens with any terraforming mod, like free terraform and paint anywhere mods, might be a game limitation, but thought i should report it still and maybe you guys find a workaround.
Thanks. :)

**Comment by Dzi4d3k** [comment]
Sounds similar to:
https://github.com/scfmod/FS22_TerraFarm/issues/26
