### ISSUE TITLE
Changing fill type, not being able to dig

### ISSUE THREAD

**Issue by scfmod** [scfmod/FS22_TerraFarm#4]
I.e if you have dirt in your bucket and change to stone it will not discharge or modify the landscape.
Will be fixed with automatically changing the filltype in all buckets next update.

In the meantime make sure you empty your bucket.
(Discharging into trailers etc. should work as normal)

**Comment by Eddievick** [comment]
Was just testing this, not possible to tip to ground from a trailer full of dirt, is that because dirt isn't recognised as a fill type on the map?

**Comment by scfmod** [comment]
Yep, I'll look into if it can be easily fixed

**Comment by FSMiner1** [comment]
HI I'm FS Miner please contact me at my discord or fb https://discord.gg/qbKr9zs
I have ready but not public a dozer and a roller I can give them to add in your amazing terrafarm mod:)
