### ISSUE TITLE
Using Terrafarm with explosives, solves a lot of matters

### ISSUE THREAD

**Issue by JohannesSpg** [scfmod/FS22_TerraFarm#40]
New to Github, so i hope i placed it in the right spot.....
I am thinking a few days about the Terrafarm mod now.
And i wonder if it can be transformed into a kind of explosive, where you dig holes in game.
Fill these holes with ANFO, Ammonium Nitrate and Fuel Oil.
Then attach a detonator to the hole(s), in effect the terrafarming device....
Blow it up and at the moment of detonation the terrafarming takes place.
Yes it requires some mods to develop like drilling rigs, ANFO truck and most of all the detonators, but it prevents that every digger have to be added individually to the compatibilty list or whatever, it can simplify things a lot.
Diesel (Fuel Oil) and Fertilizer (Ammonium Nitrate) we already have in game, just need to develop 3 mods basically and the terrafarm mod itself.
After the blow up, you can dig up the converted terrafarmed dirt, stone or whatever.
It comes closest to real life mining and can be used to terrafarm sections of land big or small.
1 hole or 100 holes depending on the system FS runs on and how fast it is.
Just an idea.

**Comment by scfmod** [comment]
It's definitely doable to make, but would make more sense to have it as a separate mod :-)
You only need to calculate your destruction radius/shape, and alter the density map for terrain height accordingly plus the density map for the fill type.
g_densityMapHeightManager should have most of the values and functions you need

**Comment by JohannesSpg** [comment]
To be honest, i can't make mods myself.
So i have to see if i can gather the right people to help me create this and i think i know already who can do it.
To me it sure sounds like a fun idea and i am thankful for your reply and thinking with me.
Now i need to sleep, it is 1:40 am here lol

**Comment by JohannesSpg** [comment]
Thinking to what we can tie the terrafarming script, can it be made like this that the blast radius is for example 5 or 10 meters, perhaps both?
And is it possible to have the script on a detonator so we can create is as a separate mod as suggested?
Because i am thinking of using this as a batch of 1 piece to a 100 or even more, each with a blast/terrafarming radius of 5 or 10 meters, this means for instance when you use 100 of them an area of 500 or 1000 square meters and a depth of 5 or 10 meters would release a maximum of 10.000 cubic meters if i am correct. Maybe it is too much lol.

**Comment by Dzi4d3k** [comment]
@JohannesSpg 
Please don't get me wrong, but modding doesn't work in such way as you doing right now. You simply can't come to a skilled modder and ask him or even propose to do any mods.
Modding is a pice of passion and it is done in modder's free time and obviously on what he willing to work on.
That is general idea, of course modders are often open for suggestions, but that's it.

**Comment by JohannesSpg** [comment]
Got ya, case closed then.
End of story.
It is a stupid idea after all.

**Comment by scfmod** [comment]
The issue with converting blast radius (m3) to a fill type, i.e stone, is that the ground density has a height limit.
So there's only x amount of liters of stone you can have per m2 on the ground.

**Comment by Dzi4d3k** [comment]
@JohannesSpg No I don't mind that this is bad idea, in fact I think it's good idea. And from what I see @scfmod is more than helpful on your idea. Believe me or not, but with many other modders you would meet with rough attitude to such propositions.
As you wrote, that you are new to GitHub, so it's not bad to ask and discus about mods and enhancements, but it's not welcome to see demands.
I believe that is not excluded that @scfmod (of course I don't want to speak on his behalf) could consider you ideas as future enhancements, however at current state there are lot of base functionalities at the top of priority list :)

**Comment by scfmod** [comment]
No toes got mutilated 😅 I won't be adding such a feature to TerraFarm as it's more focused on machines :-)
But the idea is interesting, and totally feasible to code. Bascially everything you'd need to make this work is in the DensityMapHeightManager class.

**Comment by JohannesSpg** [comment]
scfmod, maybe you can make a stick of dynamite to test it out lol.

**Comment by JohannesSpg** [comment]
There are more people who like the idea, so i reopened it.
Any suggestions as to how to make it work are welcome.
Not need modders with an attitude, act normal is already bad enough lol.
Just looking for ideas and suggestions, not heavy debates about ethics.

**Comment by scfmod** [comment]
Closing this issue.
I added the Discussions feature to the repository so that you can use that instead of Issues section :-)

**Comment by JohannesSpg** [comment]
Would be nice if this is brought over to Discussions then....
