### ISSUE TITLE
Thanks for this project (I don't know where else to put this)

### ISSUE THREAD

**Issue by seriousmods** [scfmod/FS22_TerraFarm#41]
Hello,

I'd like to offer my appreciation as a long-time Farming Simulator player and fan for this project. I have been unable to find a way to message you, so I figured I'd post it here. 

I also have an idea to suggest if you have any interest, but again, not sure where to post it. Feel free to message me via facebook (my page name is the same as my username). Again, thank you!

**Comment by scfmod** [comment]
I added Discussions feature to the repository now, so feel free to open a topic there.
Closing this issue.
