### ISSUE TITLE
Cant find mod ingame

### ISSUE THREAD

**Issue by Six10Zone** [scfmod/FS22_TerraFarm#5]
hi, i cant find the mod when i start the game, i have added it in mod folder. is it somthing mor i need to do?

**Comment by scfmod** [comment]
Download FS22_TerraFarm.zip from Releases, not a copy of the GitHub repository :-)

https://github.com/scfmod/FS22_TerraFarm/releases

**Comment by Six10Zone** [comment]
ah okay, thanks :-)
