### ISSUE TITLE
Thank you for this mod!

### ISSUE THREAD

**Issue by TheDukeOne** [scfmod/FS22_TerraFarm#50]
I Have to say thank you for this brillant mod. After some testings with this, i was so happy with this so that i build my whole Farmyard with it. Thanks for this Masterpiece.

Sorry for nonesense issue, but i want to save that you read it.

**Comment by scfmod** [comment]
Thank ye for the kind words :-) It's always fun to see that others find the mod useful

**Comment by TheDukeOne** [comment]
I'm so hyped when the dozer will b able to work with terrafarm.

**Comment by TheDukeOne** [comment]
Yeah, he has released but we have to wait for 4.0.

**Comment by cdawg85** [comment]
Yeah I'm waiting for 4.0 so I can get it working on my dedicated server lol
