### ISSUE TITLE
Use releases for betas (pre-release)

### ISSUE THREAD

**Issue by Dylan-M** [scfmod/FS22_TerraFarm#51]
FS Miner dropped a video today with a mediafire link in the desc for this mod's 4.0 version.

If this is supposed to be publicly available, it would be better if it was done here on GitHub (which most of us consider the official source for this mod) as a pre-release.

This can be done in the releases section via a simple checkbox. This would avoid any confusion and distrust. Some of us are trying very hard to only download mods from official sources to support the author, in this case you.

Thank you!

**Comment by Dzi4d3k** [comment]
Well for me it looks like FS Miner is one of the modders which are so impatient to wait for original modders, so they start do do forks of mods introducing different version with own numbering that confuses regular users:
https://github.com/scfmod/FS22_TerraFarm/issues/4#issuecomment-1005234412

**Comment by scfmod** [comment]
I gave FSMiner permission to share a version I sent him earlier so that people that wanted can play with it if they want to until I have time to work on release version.
Closing this issue.
