### ISSUE TITLE
0.04 Beta

### ISSUE THREAD

**Issue by alexanderweide** [scfmod/FS22_TerraFarm#52]
Hey,

i have installed the beta 0.04 and i found out a slight issue that should be rethought -> when i use the EC Excavator from Volvo i get the visual doubled or trippled amount of Dirt in the bucket but raising the terrain is only a fraction of it.. : 

i made some changes to fix that for me:

in the file terrafarmlandscaping.xml i doubled the raise defaults:

if operation == TerraFarmLandscaping.OPERATION.LOWER then
        deform:enableAdditiveDeformationMode()
        deform:setAdditiveHeightChangeAmount(-0.005)
    elseif operation == TerraFarmLandscaping.OPERATION.RAISE then
        deform:enableAdditiveDeformationMode()
        deform:setAdditiveHeightChangeAmount(0.01)
    elseif operation == TerraFarmLandscaping.OPERATION.FLATTEN then
        deform:setAdditiveHeightChangeAmount(0.005)
        deform:setHeightTarget(target.y, target.y, 0, 1, 0, -target.y)
        deform:enableSetDeformationMode()

best regards

**Comment by Dzi4d3k** [comment]
@alexanderweide where you got 0.4 version, because it is not available yet here on GitHub?
Am I missing something, and @scfmod abandoned GitHub and published TerraFarm mod somewhere else, or you got unauthorized (modified) version of mod and came here for support for version which is not released by author?

**Comment by scfmod** [comment]
See #51 
The version is not supported as it's not the same as my dev branch.
Closing this issue.

**Comment by scfmod** [comment]
Not closing the issue because of your original post @alexanderweide thanks for reporting your find :-)
