### ISSUE TITLE
0.04 settings - need to be moved to dedicated server admin only

### ISSUE THREAD

**Issue by alexanderweide** [scfmod/FS22_TerraFarm#53]
Hey,

I found out that the settings for unloading as well as other options can be set on a player by player basis on the server. -> the problem with that is that dedicated players are able to cheat because of those settings.

it would probably be better to make those settings only avaliable for administrators of dedi servers.

in the filltypes xml i added more values to exclude cheatable options such as:

TerraFarmFillTypes.EXCLUDE = {
....

    ['LIME'] = true,
    ['SNOW'] = true,
    ['ROADSALT'] = true,
    ['MANURE'] = true,
    --[''] = true,

**Comment by scfmod** [comment]
Various permissions for MP is planned for 0.7.0.0, but it could be a long way away and not prioritized.
Closing this issue for now.
