### ISSUE TITLE
terra farm will not run 

### ISSUE THREAD

**Issue by ambu684** [scfmod/FS22_TerraFarm#59]
downloaded and enabled but do not get the option to use ( I'm using fs miner's mods I've tried it on calmlands, elmcreek, and a couple of others with no success. There is a distinct possibility I'm just missing something simple but Im at wits end as to getting it working thanks for the mod and you time.

**Comment by turnerd20** [comment]
what do you mean by it won't run? are you using the correct machinery? if your looking for the wash plants etc for mining they are in the Yukon Valley mod map I also suggest grabbing some of FSminer's vehicles

**Comment by ambu684** [comment]
Yes fsminers stuff is what I'm using my intent was road building, but I do
not get the menus for terrafarm when in the equipment, I have the mod
activated and confirmed my equipment is correct. Sorry to be a bother

**Comment by ambu684** [comment]
The issue is resolved on the 3rd install it just works now have no idea why or what the issue was. again thanks for your hard work on the mod.

**Comment by 12Impreza** [comment]
I can't dig with terraform on Wyoming fs22
