### ISSUE TITLE
Where to download 0.4.0 ?

### ISSUE THREAD

**Issue by Jayshua83** [scfmod/FS22_TerraFarm#60]
I keep seeing 0.4.0 listed everywhere and people are sharing it. 

Where is the actual download of it? 

Why is nothing listed here on it or download/progress of it?

Is someone else doing it, is it NOT being developed anymore? Is it a hidden repo?

**Comment by blackwellj** [comment]
It looks like work here has stalled. No updates for 3 months :(

**Comment by ar4s01** [comment]
unfortunettly i found beta version in one of fsminer packs... ofc aggregate site [https://www.modhub.us/farming-simulator-22-mods/terrafarm-and-fsm-terramods]

**Comment by scfmod** [comment]
v0.4.0.0 was put on hold on my side due to lack of time, and now it being a really old version I gave FSMiner permission to publish it won't be released here. v0.5.0.0 is going to be the next official release :)
