### ISSUE TITLE
Version 0.5.0.0

### ISSUE THREAD

**Issue by scfmod** [scfmod/FS22_TerraFarm#65]
**Update**
The current "unofficial" 0.4.0.0 beta will no longer be supported and will be phased out with the upcoming 0.5.0.0 release instead.
This means 0.4.0.0 will not be officially released considering it's a very old copy of the old development branch and to avoid confusion with versioning.

For 0.5.0.0 progress I have updated the repository project:
https://github.com/scfmod/FS22_TerraFarm/projects/1

(Note: this does not mean that machine configuration updates from FSMiner for the old 0.4.0.0 won't happen)

**Comment by SCP-Trump** [comment]
so at the moment 0.5.0.0 is not currently available right?

**Comment by scfmod** [comment]
Correct, I'm hoping to release 0.5.0.0 before end of year but nothing certain yet

**Comment by SCP-Trump** [comment]
Alright, so as of right now there is no way to add buckets or attachments (for dummies btw) to the mod? Because there is a mod that just got released for the DLC Excavators and I think its the best thing since sliced bread soo it would be MIIIIIIINT to have terra farm on that HOE!

**Comment by Bjoern-Berlin** [comment]
Hallo scfmod Team. Kann man einen Bodentexturen Mod erstellen?
Also auf normalen Karten kann ich diese selber (wissen erforderlich) einfügen. Aber bei DLC Karten (Silverrun Forrest) nicht.
Die Bodentexturen sind mir zu wenig und gefallen mir nicht.
LG Björn

**Comment by RickSanchez56** [comment]
any updates on this?

**Comment by gerador20** [comment]
did the mod die ?

**Comment by TheAshladzz** [comment]
> did the mod die ?

Not dead, as the dev posted on another issue here the other day. But pretty sure it has been on hold because of reasons. Also with the recent cliffhanger regarding a new FS game, many devs put their projects on hold at the moment waiting to see if it eill be another game to mod on👌
