### ISSUE TITLE
Multiplayer Issues

### ISSUE THREAD

**Issue by possessedzZ** [scfmod/FS22_TerraFarm#66]
Any fix yet for multiplayer fill types? Cannot use dirt at all on my server.

**Comment by scfmod** [comment]
Which version are you using? And does the map have support for dirt filltype?

**Comment by majorhatter** [comment]
iam on elmcreek map right now its not working on my multiplayer

**Comment by majorhatter** [comment]
i have the newest version downloaded

**Comment by majorhatter** [comment]
guess ill try 3.5

**Comment by possessedzZ** [comment]
I got it to work, I switched over to Yukon valley map and it seems to be
working so far.
