### ISSUE TITLE
[Vehicles] Trying to add discard/ dump function to trailers,  

### ISSUE THREAD

**Issue by DirtyDieselDriftNZ** [scfmod/FS22_TerraFarm#7]
Trying to add discard/ dump function to trailers, can't get to bring up current modes in the on screen hud, but all else is working

**Comment by scfmod** [comment]
I have not added support for trailers yet, will look into it for next update.
Note that if you are trying to dump i.e dirt that isn't natively added by map it don't work due to it not having set up a density map for given material. That is being looked into as well

**Comment by SuprDave** [comment]
The only way you can discard / dump from trucks or trailers you need to add the fruitTP to your map.. I added it to all the maps I played on and used the terrafarm 3.6.0 and I can dump anywhere that I own the land. this terrafarm is awesome you've changed the game big time.
