### ISSUE TITLE
Latest version Farming simulator, Still dosent work. 

### ISSUE THREAD

**Issue by Vitze** [scfmod/FS22_TerraFarm#74]
I downloaded from the releases page, and updated my farming sim. It shows up in the selection screen but does not work in game. There is no key bind settings, Z wont open any menus. I thought maybe another mod was conflicting so i removed every single mod and only have TerraFarm enabled on 1.8.2 of farm sim. No matter what it will not work in game. No key bind settings or menu to open.

**Comment by Vitze** [comment]
No modded maps, just DLC enabled kubatoa pack and platinum.

**Comment by Vitze** [comment]
Tried almost every version of FS and could not get it to work, tried FS miners version of this mod, could not get it working, Finally after trying almost 5 different versions this outdated one from a random site seems to work fine. https://fs22.com/farming-simulator-22-mods/scripts-and-tools/terrafarm-v0-4-mce/ I am doing nothing different on install, these version on GitHub or others just did not work for me.

**Comment by FSShay** [comment]
Same thing for me, I downloaded it exactly how every guide says to, I can see that the mod is installed and it shows up before loading into game. when I get into game there are no key binds showing up for the mod in the keyboard controls tab. I have tried starting a new game and only having the mod activated for that game and I still get no key binds for the mod.

**Comment by samjampen** [comment]
has anyone found a solution to this im having a Simler issue except it is saying the maps density size is unsupported, cant dig any ground and it wont let me empty any of the resources shown onto the ground
