### ISSUE TITLE
Please Help me

### ISSUE THREAD

**Issue by CiggaWeed828** [scfmod/FS22_TerraFarm#8]
ive downloaded the mod as zip file, says i have mod in the "installed" section on fs22 but when i goto load my save theres nothing in there.

**Comment by HrNox** [comment]
I have the same problem, I have tried almost everything over time.

**Comment by CiggaWeed828** [comment]
i just sussed it, you have to download github then download the file through that then put it in mod folder, worked for me after.

**Comment by scfmod** [comment]
Updated the README with instructions on how to download the correct file, hope it clears up any confusion :-)
