### ISSUE TITLE
Not Working In Game

### ISSUE THREAD

**Issue by CritRz** [scfmod/FS22_TerraFarm#88]
1. I put the .zip folder into the game mod folder.
2. The option to select it on the mod selection screen is there and selected.
3. In game, the key binds are present in the key bind option screen.
4. When I press "I", nothing happens. It does not open the TerraFarm menu.
5. When I enter a supported base game vehicle with a supported attachment (i.e. bucket), the key binds still do nothing and the display does not appear.
6. Uninstalled the game.
7. Deleted all files associated to the game.
8. Reinstalled game.
9. Only placed the TerraFarm mod .zip file.
10. Ran again on Elm Creek.
11. Steps 3-5 above hold true.
12. Repeated steps 6-10 with latest release from this project as well as, FS22_TerraFarm_MCE_10.zip, FS22_TerraFarm_4x.zip, FS22_TerraFarm_16x.zip from RealisticGamingCrew, FS22_TerraFarm_MCE_V11.zip, FS22_TerraFarm_MCE_V10.zip, FS22_TerraFarm_MCE_V0_9.zip, FS22_TerraFarm_MCE_0_8.zip, FS22_TerraFarm_MCE_V0_7.zip, FS22_TerraFarm_MCE_NEW.zip, FS22_TerraFarm_MCE_0_5.zip, FS22_TerraFarm_MCE.zip from FSMiner.
-The same issues remain. Any ideas? Anyone? I think the mod is amazing from what I have seen with it working on YouTube, but I have yet to get it to work.

I have also tried using different key binds, still the same.

**Comment by CritRz** [comment]
Forgot to mention what I am running. I am using the latest v1.13.1 from Steam with the Platinum Expansion, but not the Premium Expansion.

**Comment by Comet051091** [comment]
uh i accidently disabled terrafarm in my global settings is there a way to turn it back on i've tried to uninstall and re install it but it dosent help

**Comment by Comet051091** [comment]
is this what i have to do to get a machine to work with terrafarm? and if the xml is already in the index then do i just add the xml file to the xml config of the main terrafarm file?
https://www.youtube.com/watch?v=WJubZDU0l20

**Comment by OfficerCadbury** [comment]
> uh i accidently disabled terrafarm in my global settings is there a way to turn it back on i've tried to uninstall and re install it but it dosent help ![image](https://private-user-images.githubusercontent.com/48610435/286202322-34fc7831-8881-4cb0-af5d-339dafd99f1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDgzNjAsIm5iZiI6MTcxOTE0ODA2MCwicGF0aCI6Ii80ODYxMDQzNS8yODYyMDIzMjItMzRmYzc4MzEtODg4MS00Y2IwLWFmNWQtMzM5ZGFmZDk5ZjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEzMDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZGFhOTNkYmY2MTI4ODE3ZmJlMjA3ZWIzOTI3NWU1MmI3MDc1YTE1YzFmNmQ5NmU3YTUyZGVmNTkwYjA2ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KSU3VU-iNYrbSLik6_oJ3bZFxlgqObIBK7go1r5tWGE) i cant get access to this menu for ref

Were you able to find where this menu is? I can't find it either.
