### ISSUE TITLE
add and remove bucket collision on excavator is the same key bindings as the mode

### ISSUE THREAD

**Issue by SuprDave** [scfmod/FS22_TerraFarm#9]
is there a way to get the key binding (x or L1+A) separated between removing collision and the mode.. in multiplayer you can't remove the collision on the excavator bucket that is the only thing me and brother experienced last night while playing.. so it makes the excavator kind of useless.. besides that it's an awesome mod.

**Comment by scfmod** [comment]
We'll see later down the road if there's still conflicts, not a priority right now :-) In the meantime you can edit the keybinds manually for removing the collision.

**Comment by Hevdig2v** [comment]
and where can i change the key assignment? I've looked through everything and haven't found anything yet, use the Liebherr 926.
