### ISSUE TITLE
TerraFarming with Albutt ID#581

### ISSUE THREAD

**Issue by TheAshladzz** [scfmod/FS22_TerraFarm#95]
Hello there! :)

I am trying to use the Albutt bucket on my front loader, but it does not paint the ground when using smooth, flatten or lower.
It's set to Stones in the material. And GravelDustLight in the Terraform/Discharge section. Works well on Magsi buckets for the bigger wheel loaders.

**Comment by scfmod** [comment]
Hi there :-)
If I remember correctly there was some issues using the small front loader shovels, but I can't remember the specific version. Most likely you are using the 0.3.6.0 version?

**Comment by TheAshladzz** [comment]
> Hi there :-)
> If I remember correctly there was some issues using the small front loader shovels, but I can't remember the specific version. Most likely you are using the 0.3.6.0 version?

Hello there! ☺ Thank you for your swift reply! I will certainly check what version i am running atm. But my guess it is the latest version atleast ☺ Good to see you back btw!
