### ISSUE TITLE
Showing filltype and choosing it OTF with keybind

### ISSUE THREAD

**Issue by TheAshladzz** [scfmod/FS22_TerraFarm#99]
Hello there again :) Not a issue, but just a question out of curiosity! I am playing a bit around - and im having this idea that it would be cool to be able to on my controller for example - change fillType on the fly and also be able to show what filltype choosen on the HUD.

I was thinking maybe to try to map buttons to the TerraFarm settings where you choose fillType. Is this possible you think? :)

**Comment by scfmod** [comment]
Hi there, I added HUD filltype icon and keybindings for showing filltype/paint select dialog in the upcoming version today :-)

**Comment by TheAshladzz** [comment]
> Hi there, I added HUD filltype icon and keybindings for showing filltype/paint select dialog in the upcoming version today :-)

What, really! 😃 That made my day! 😺 Can't wait to see what else is new in the upcoming version! I'll buy you a beer for this one 😄

**Comment by scfmod** [comment]
👍 just to be clear the version isn't being released today 😅 but it will enter internal testing phase this week so hopefully soon :-)
